spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  file:
    name: logs/app.log
  level:
#    trace / debug / info / error 순서의 로그레벨
#    예를 들어 info로 설정할 시, trace와 debug의 레벨의 로그는 나오지 않는다.
    root: info
